package view;

/**
 *
 * @author nathália lima
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        setSize(500,350);
        setLocationRelativeTo(null); // centraliza janela
        getContentPane().setBackground(java.awt.Color.WHITE);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelCadastro = new javax.swing.JPanel();
        panelTopo = new javax.swing.JPanel();
        labelSistema = new javax.swing.JLabel();
        labelCadastrar = new javax.swing.JLabel();
        labelDasdosCliente = new javax.swing.JLabel();
        labelNomeCliente = new javax.swing.JLabel();
        campoNomeCliente = new javax.swing.JTextField();
        labelCpf = new javax.swing.JLabel();
        campoCpf = new javax.swing.JTextField();
        labelNumeroCelular = new javax.swing.JLabel();
        campoNumeroCelular = new javax.swing.JTextField();
        labelDadosVeiculo = new javax.swing.JLabel();
        labelTipoVeiculo = new javax.swing.JLabel();
        labelModeloVeiculo = new javax.swing.JLabel();
        campoModeloVeiculo = new javax.swing.JTextField();
        labelPlaca = new javax.swing.JLabel();
        campoPlaca = new javax.swing.JTextField();
        labelCor = new javax.swing.JLabel();
        campoCor = new javax.swing.JTextField();
        labelDadosOficina = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        campoDia = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        campoMotivo = new javax.swing.JTextField();
        bSlavar = new javax.swing.JButton();
        labelDiagnostico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDiagnostico = new javax.swing.JTextArea();
        bLimpar = new javax.swing.JButton();
        cbTipoVeiculo = new javax.swing.JComboBox<>();
        labelAnoVeiculo = new javax.swing.JLabel();
        campoAnoVeiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 350));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelCadastro.setBackground(new java.awt.Color(255, 255, 255));
        panelCadastro.setPreferredSize(new java.awt.Dimension(500, 1000));

        panelTopo.setBackground(new java.awt.Color(0, 0, 0));
        panelTopo.setPreferredSize(new java.awt.Dimension(146, 34));

        labelSistema.setBackground(new java.awt.Color(0, 0, 0));
        labelSistema.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSistema.setForeground(new java.awt.Color(255, 255, 255));
        labelSistema.setText("Sistema de Oficina");

        javax.swing.GroupLayout panelTopoLayout = new javax.swing.GroupLayout(panelTopo);
        panelTopo.setLayout(panelTopoLayout);
        panelTopoLayout.setHorizontalGroup(
            panelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSistema)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTopoLayout.setVerticalGroup(
            panelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSistema)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        labelCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCadastrar.setText("CADASTRAR VEÍCULO");

        labelDasdosCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDasdosCliente.setText("Dados do cliente ");

        labelNomeCliente.setText("Nome do cliente");

        labelCpf.setText("CPF");

        labelNumeroCelular.setText("Número de celular");

        labelDadosVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDadosVeiculo.setText("Dados do veículo");

        labelTipoVeiculo.setText("Tipo do veículo");

        labelModeloVeiculo.setText("Modelo do veículo");

        labelPlaca.setText("Placa");

        labelCor.setText("Cor");

        labelDadosOficina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDadosOficina.setText("Dados da oficina");

        labelDia.setText("Dia que chegou");

        campoDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel2.setText("Motivo da entrada");

        bSlavar.setBackground(new java.awt.Color(0, 0, 0));
        bSlavar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSlavar.setForeground(new java.awt.Color(255, 255, 255));
        bSlavar.setText("Salvar");
        bSlavar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelDiagnostico.setText("Diagnóstico do mecânico");

        campoDiagnostico.setColumns(20);
        campoDiagnostico.setRows(5);
        jScrollPane2.setViewportView(campoDiagnostico);

        bLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bLimpar.setText("Limpar");
        bLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", " " }));

        labelAnoVeiculo.setText("Ano do veículo");

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(bSlavar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(labelDia)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel2))
                            .addComponent(labelAnoVeiculo)
                            .addComponent(labelCadastrar)
                            .addComponent(labelDadosVeiculo)
                            .addComponent(labelDadosOficina)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDasdosCliente)
                                    .addComponent(labelNomeCliente)
                                    .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTipoVeiculo)
                                    .addComponent(cbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelCpf))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelNumeroCelular)
                                            .addComponent(campoNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelModeloVeiculo)
                                            .addComponent(campoModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                                .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64)
                                                .addComponent(labelCor))
                                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                                .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(labelDiagnostico))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoAnoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 186, Short.MAX_VALUE))))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addComponent(panelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCadastrar)
                .addGap(18, 18, 18)
                .addComponent(labelDasdosCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomeCliente)
                    .addComponent(labelCpf)
                    .addComponent(labelNumeroCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(labelDadosVeiculo)
                .addGap(18, 18, 18)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoVeiculo)
                    .addComponent(labelModeloVeiculo)
                    .addComponent(labelPlaca)
                    .addComponent(labelCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoModeloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAnoVeiculo)
                .addGap(3, 3, 3)
                .addComponent(campoAnoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDadosOficina)
                .addGap(18, 18, 18)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDia)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelDiagnostico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSlavar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 406, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(panelCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSlavar;
    private javax.swing.JTextField campoAnoVeiculo;
    private javax.swing.JTextField campoCor;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JFormattedTextField campoDia;
    private javax.swing.JTextArea campoDiagnostico;
    private javax.swing.JTextField campoModeloVeiculo;
    private javax.swing.JTextField campoMotivo;
    private javax.swing.JTextField campoNomeCliente;
    private javax.swing.JTextField campoNumeroCelular;
    private javax.swing.JTextField campoPlaca;
    private javax.swing.JComboBox<String> cbTipoVeiculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAnoVeiculo;
    private javax.swing.JLabel labelCadastrar;
    private javax.swing.JLabel labelCor;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDadosOficina;
    private javax.swing.JLabel labelDadosVeiculo;
    private javax.swing.JLabel labelDasdosCliente;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDiagnostico;
    private javax.swing.JLabel labelModeloVeiculo;
    private javax.swing.JLabel labelNomeCliente;
    private javax.swing.JLabel labelNumeroCelular;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelSistema;
    private javax.swing.JLabel labelTipoVeiculo;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelTopo;
    // End of variables declaration//GEN-END:variables
}
